site_name: Vedant's Dev Notes
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - toc.integrate
    - navigation.top


  #logo: fontawesome/brands/twitter
  #favicon: images/favicon.png
  font:
    text: Inter
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/regular/user-circle
      link: https://www.vedantlohbare.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/vedantlohbare
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vedant-lohbare/
    - icon: fontawesome/brands/github
      link: https://github.com/vedant14/dev-notes
    - icon: fontawesome/brands/strava
      link: https://www.strava.com/athletes/25910894
site_name: My Docs
